### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by buzinas** [pickuppdev/react-native-opencv#1]
Hey there, I was wondering:

Is this a working in progress, is it ready for use, what is the current status?

**Comment by viuts** [comment]
hi there, this is an internal project and the usage is quite limited for now. We did some basic wrapper on some common used algorithms like laplacian, etc. You can use those if ur usage is similar, we are already using it in production app.

We also welcome PRs, but this repo will not be actively maintained.

**Comment by mobtex** [comment]
This work with camera live BubbleSheet detector?
